// Code generated by mockery v2.42.3. DO NOT EDIT.

package telemetry

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPingServiceServer is an autogenerated mock type for the PingServiceServer type
type MockPingServiceServer struct {
	mock.Mock
}

type MockPingServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPingServiceServer) EXPECT() *MockPingServiceServer_Expecter {
	return &MockPingServiceServer_Expecter{mock: &_m.Mock}
}

// PingPong provides a mock function with given fields: _a0, _a1
func (_m *MockPingServiceServer) PingPong(_a0 context.Context, _a1 *Ping) (*Pong, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PingPong")
	}

	var r0 *Pong
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *Ping) (*Pong, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *Ping) *Pong); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Pong)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *Ping) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPingServiceServer_PingPong_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingPong'
type MockPingServiceServer_PingPong_Call struct {
	*mock.Call
}

// PingPong is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Ping
func (_e *MockPingServiceServer_Expecter) PingPong(_a0 interface{}, _a1 interface{}) *MockPingServiceServer_PingPong_Call {
	return &MockPingServiceServer_PingPong_Call{Call: _e.mock.On("PingPong", _a0, _a1)}
}

func (_c *MockPingServiceServer_PingPong_Call) Run(run func(_a0 context.Context, _a1 *Ping)) *MockPingServiceServer_PingPong_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Ping))
	})
	return _c
}

func (_c *MockPingServiceServer_PingPong_Call) Return(_a0 *Pong, _a1 error) *MockPingServiceServer_PingPong_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPingServiceServer_PingPong_Call) RunAndReturn(run func(context.Context, *Ping) (*Pong, error)) *MockPingServiceServer_PingPong_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPingServiceServer creates a new instance of MockPingServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPingServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPingServiceServer {
	mock := &MockPingServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
